name: qlevar_router
description: Use a clever router. Manage your project routes. Create nested routes. navigation without context to your pages. Change only one sub widget on your page when navigating to the new route.


version: 1.1.2
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.2