name: qlevar_router
description: A router that helps you to manage your project routes. Create nested routes. navigation without context between your pages.

version: 1.4.2
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0