name: qlevar_router
description: With Navigator2.0 update only one widget in your page when navigating to new route. Manage your project routes and create nested routes. Simply navigation without context to your page.
version: 0.2.0
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
