name: qlevar_router
description: A router that helps you to manage your project routes. Create nested routes. navigation without context between your pages.

version: 1.11.2
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

topics:
  - navigation
  - middleware
  - nested-routes
  - deep-linking
  - qlevar-router