name: qlevar_router
description: Manage your project routes and create nested routes.
version: 0.1.0
repository: https://github.com/SchabanBo/qlevar_router

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
