name: ci

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
       channel: 'master'
    - run: flutter pub get
    - run: flutter format .
    - run: flutter analyze
    - run: flutter test
