name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        channel: stable
    - run: flutter pub get
    - run: dart format --set-exit-if-changed .
    - run: flutter analyze
    - run: flutter test --coverage
    - uses: codecov/codecov-action@v5
      with:
        files: coverage/lcov.info
        token: ${{ secrets.CODECOV_TOKEN }}
